# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout code nya~
      uses: actions/checkout@v4

    - name: add msbuild to path rawr~
      uses: microsoft/setup-msbuild@v1.0.2

    - name: install vcpkg nya~
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: install zlib + curl with vcpkg uwu
      run: .\vcpkg\vcpkg.exe install zlib:x64-windows curl:x64-windows

    - name: restore nuget packages :3
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: build with msbuild and zlib/curl support~ 💜
      run: |
        $vcpkgRoot = "${{github.workspace}}\vcpkg\installed\x64-windows"
        $includeDir = "$vcpkgRoot\include"
        $libDir = "$vcpkgRoot\lib"
        echo "INCLUDE DIR: $includeDir"
        echo "LIB DIR: $libDir"
        msbuild /m `
                /p:Configuration=${{env.BUILD_CONFIGURATION}} `
                /p:Platform=x64 `
                /p:AdditionalIncludeDirectories="$includeDir" `
                /p:AdditionalLibraryDirectories="$libDir" `
                /p:AdditionalDependencies="zlib.lib;libcurl.lib" `
                ${{env.SOLUTION_FILE_PATH}}
